name: build
run-name: Build Massgate Server
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - run: cmake -A Win32 -S . -B build
      - run: cmake --build build
